### ISSUE TITLE
 No module named 'ChatApp'

### ISSUE THREAD

**Issue by dhgouveia2** [microsoft/Llama-2-Onnx#37]
when trying to execute the ChatApp/app.py from Windows powershell

```powershell
$ python ChatApp/app.py
```

I got the following error. 
```python
Traceback (most recent call last):
  File "C:\Llama-2-Onnx\ChatApp\app.py", line 6, in <module>
    from interface.hddr_llama_onnx_interface import LlamaOnnxInterface
  File "C:\Llama-2-Onnx\ChatApp\interface\hddr_llama_onnx_interface.py", line 12, in <module>
    from ChatApp.app_modules.utils import (
ModuleNotFoundError: No module named 'ChatApp'
```

Dependencies have been  installed
````python
cd .\ChatApp
pip install -r requirements.txt
````

```powershell
$ python -V
Python 3.10.6
```

**Comment by Nancyberry31** [comment]
#37
![Uploading Screenshot_20231113-155858~2.jpg…]()

**Comment by meetrais** [comment]
> when trying to execute the ChatApp/app.py from Windows powershell
> 
> ```powershell
> $ python ChatApp/app.py
> ```
> 
> I got the following error.
> 
> ```python
> Traceback (most recent call last):
>   File "C:\Llama-2-Onnx\ChatApp\app.py", line 6, in <module>
>     from interface.hddr_llama_onnx_interface import LlamaOnnxInterface
>   File "C:\Llama-2-Onnx\ChatApp\interface\hddr_llama_onnx_interface.py", line 12, in <module>
>     from ChatApp.app_modules.utils import (
> ModuleNotFoundError: No module named 'ChatApp'
> ```
> 
> Dependencies have been installed
> 
> ```python
> cd .\ChatApp
> pip install -r requirements.txt
> ```
> 
> ```powershell
> $ python -V
> Python 3.10.6
> ```

I resolved this error by removing "**ChatApp.**" where ever its referred.

For example, Change This -> from ChatApp.app_modules.utils import

To -> from app_modules.utils import

**Comment by iclaxton** [comment]
To resolve you will need to do the following:

Windows:
`SET PYTHONPATH=.`

Mac/Linux
`export PYTHONPATH=.`

This should be added to the documentation or fixed in the project via config
